v1.0.3

diff --git a/gsshs b/gsshs
--- a/gsshs
+++ b/gsshs
@@ -10,8 +10,18 @@ if [ $# -ne 2 ]; then
 fi
 
 if ! command -v git &> /dev/null; then
-    echo "Error: git is not installed."
-    exit 1
+    if command -v apt &> /dev/null; then
+        echo "Info: APT package manager detected. Root privilages are required to installed git:"
+        sudo apt update
+        sudo apt install -y git
+    elif command -v dnf &> /dev/null; then
+        echo "Info: DNF package manager detected. Root privilages are required to installed git:"
+        sudo dnf update
+        sudo dnf install -y git
+    else
+        echo "Error: Unknown package manager. Git can not be installed automatically. Please install git before using gsshs."
+        exit 1
+    fi
 fi
 
 git config --global user.name "$2"
@@ -31,7 +41,7 @@ if [[ "$(uname)" != "Darwin" ]]; then
             sudo dnf update
             sudo dnf install -y xclip
         else
-            echo "Error: Unknown package manager. xclip can not be installed automatically. Please install xclip before using gsshs."
+            echo "Error: Unknown package manager. Xclip can not be installed automatically. Please install xclip before using gsshs."
             exit 1
         fi
     else
